FROM alpine:edge
ENV GOPATH=/home/jump/go/bin
RUN apk update
RUN apk add go go-tools git make musl-dev musl musl-utils #python3
RUN adduser -h /home/jump/ -D jump jump
COPY . /home/jump/
RUN chown -R jump:jump /home/jump
WORKDIR /home/jump
RUN go get -u github.com/eyedeekay/gosam
USER jump
RUN make
CMD ./bin/thirdeye
